steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/report-conversion', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/report-conversion' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'report-conversion',
        '--image',
        'gcr.io/$PROJECT_ID/report-conversion',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
      '--service-account',
       '482552972428-compute@developer.gserviceaccount.com'
     ]

images:
  - 'gcr.io/$PROJECT_ID/report-conversion'