name: Cloud Build

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Cloud Build
        uses: google-github-actions/cloudbuild-deploy@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          cloudbuild_file: cloudbuild.yaml